apiVersion: apps/v1
kind: Deployment
metadata:
  name: invex-tarjetas
  labels:
    app: invex-tarjetas
    version: v2.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invex-tarjetas
  template:
    metadata:
      labels:
        app: invex-tarjetas
        version: v2.0.0
    spec:
      containers:
      - name: invex-tarjetas
        image: harbor.haas-230.pez.pivotal.io/demo/invex-tarjetas:v2.0.0
        ports:
        - containerPort: 80
