apiVersion: v1
kind: Pod
metadata:
  name: invex-tarjetas
  labels:
    app: invex-tarjetas
spec:
  containers:
    - name: invex-tarjetas
      image: harbor.haas-230.pez.pivotal.io/demo/invex-tarjetas
      imagePullPolicy: Always
      ports:
        - containerPort: 80